apiVersion: v1
kind: Service
metadata:
  name: currency-converter-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-converter
