apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter-deployment
spec:
  selector:
    matchLabels:
      app: currency-converter
  replicas: 1 # tells deployment to run 1 pods matching the template
  revisionHistoryLimit: 3
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: currency-converter
        image: admincoder/currency-converter:1.1.0
        ports:
        - containerPort: 8000
      - name: redis
        image: redis:3.2.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
